-- 自動產生：node scripts/build-seed.mjs（內建經典的要點底稿、閱讀測驗、審稿備註）
-- 只寫入還存在的文章（後台刪掉的經典不會被 foreign key 卡住）。
-- 要點底稿直接取代站上 LLM 產生的快取；題目只取代 AI 原稿，老師改過的（edited_by 有值）保留。

-- 桃花源記
UPDATE articles SET notes = '公有領域經典，陶淵明（東晉）。約 320 字。要點底稿與閱讀測驗為 AI 撰寫，上線前請審稿老師過目。' WHERE id = 'taohuayuan-ji' AND notes IS NULL;
INSERT INTO article_keypoints (article_id, model, data_json) SELECT 'taohuayuan-ji', 'import', '{"centralIdea":"藉漁人誤入又再也尋不回桃花源的故事，描繪一個沒有戰亂、人人安居樂業的理想社會，寄託作者對亂世的不滿與對美好生活的嚮往。","structure":"依漁人的行蹤敘事：發現桃花林（P1）→ 穿過山洞進入桃花源、所見景象（P2）→ 與村人交談、得知來歷（P3）→ 出洞後再尋不得（P4）→ 劉子驥欲往未果，以「後遂無問津者」作結（P5）。","vernacular":"東晉太元年間，武陵有個以捕魚為生的人，沿著溪水划船，忘了走多遠，忽然遇到一片桃花林，兩岸幾百步內沒有別的樹，花草鮮美，落花紛紛。他很驚奇，想走到林子盡頭。桃林在溪水源頭結束，那裡有座山，山上有個小洞口，隱約透著光。他下船從洞口進去，起初很窄，走了幾十步後忽然開闊：土地平坦，房屋整齊，有良田、美池、桑竹，田間小路交錯，雞鳴狗叫到處聽得見，老人小孩都安閒快樂。村人見到漁人大吃一驚，邀他回家殺雞擺酒款待。他們說祖先為了躲避秦朝戰亂來到這裡，從此與外界隔絕，竟不知道有漢朝，更不用說魏晉。漁人住了幾天告辭，村人叮囑他不必對外人說。漁人出來後沿路做記號，報告太守；太守派人跟他去找，卻迷了路，再也找不到。高士劉子驥聽說後打算前往，還沒成行就病死了，此後就再也沒有人去探尋了。","keyPoints":[{"id":"KP1","text":"漁人沿溪而行，偶然遇見一片沒有雜樹、落英繽紛的桃花林。","importance":"次要","paragraphs":["P1"]},{"id":"KP2","text":"穿過狹窄的山洞後豁然開朗，看見土地平曠、屋舍整齊、老少怡然自樂的村落。","importance":"核心","paragraphs":["P2"]},{"id":"KP3","text":"村人熱情款待漁人，自述祖先為避秦亂而來，從此與外界隔絕，不知有漢、魏、晉。","importance":"核心","paragraphs":["P3"]},{"id":"KP4","text":"臨別時村人叮囑「不足為外人道也」。","importance":"次要","paragraphs":["P3"]},{"id":"KP5","text":"漁人沿路做記號並報告太守，但再去尋找時迷了路，找不到桃花源。","importance":"核心","paragraphs":["P4"]},{"id":"KP6","text":"高士劉子驥想去也未能成行，此後再無人探問，使桃花源更顯虛幻。","importance":"次要","paragraphs":["P5"]}],"referenceOutline":[{"text":"發現桃花林","children":[{"text":"漁人沿溪而行，忘了路程"},{"text":"桃花林的美景"}]},{"text":"進入桃花源","children":[{"text":"穿過狹窄的山洞"},{"text":"田園景象與怡然自樂的人們"}]},{"text":"與村人相處","children":[{"text":"熱情款待"},{"text":"祖先避秦亂，與世隔絕"},{"text":"叮囑不要對外人說"}]},{"text":"再也尋不到","children":[{"text":"處處做記號、報告太守"},{"text":"迷路，找不到桃花源"}]},{"text":"結尾","children":[{"text":"劉子驥想去卻病終"},{"text":"後來再也沒有人探尋"}]}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'taohuayuan-ji')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, created_at = datetime('now');
INSERT INTO article_quizzes (article_id, model, data_json) SELECT 'taohuayuan-ji', 'import', '{"questions":[{"q":"漁人是怎麼發現桃花林的？","options":["聽村人指點特地前往","沿著溪水划船，忘了路程遠近時偶然遇見","奉太守命令去尋找","追著一隻鳥走進山裡"],"answer":1,"explanation":"第一段寫「緣溪行，忘路之遠近。忽逢桃花林」，「忽逢」表示是在不經意間偶然遇見的。","paragraph":"P1","skill":"擷取訊息"},{"q":"桃花源裡的人為什麼會住在那裡？","options":["祖先為了躲避秦朝的戰亂而搬來","被太守流放到這個地方","為了種桃花賣錢","迷路後找不到出去的路"],"answer":0,"explanation":"第三段村人「自云先世避秦時亂，率妻子邑人來此絕境，不復出焉」。","paragraph":"P3","skill":"擷取訊息"},{"q":"「乃不知有漢，無論魏晉」這句話最能說明什麼？","options":["村人不喜歡談論政治","村人故意假裝不知道外面的事","村人與外界隔絕已久，不知道朝代已經更替","村人認為漢朝比魏晉好"],"answer":2,"explanation":"他們秦朝時就進來，連後來的漢朝都不知道，更不用說漢以後的魏、晉，可見與世隔絕的時間非常久。","paragraph":"P3","skill":"推論分析"},{"q":"漁人出洞時「處處誌之」，太守派人跟去卻「遂迷，不復得路」。這樣安排有什麼效果？","options":["說明漁人的記性很差","讓桃花源顯得虛幻難尋，更像一個理想中的世界","批評太守辦事不力","表示山路太危險，不適合前往"],"answer":1,"explanation":"明明做了記號卻找不到，接著劉子驥也「未果」，桃花源因此若有若無，呼應它是作者心中的理想世界，而不是真實可到的地方。","paragraph":"P4","skill":"詮釋整合"},{"q":"作者透過桃花源，最想表達哪一種嚮往？","options":["四處探險、發現寶藏的生活","在朝廷做官、受到重用","熱鬧繁華的城市生活","沒有戰亂、人人安居樂業的社會"],"answer":3,"explanation":"桃花源裡良田美池、雞犬相聞、黃髮垂髫怡然自樂，而村人正是為了躲避戰亂才來，表現作者對和平安樂社會的嚮往。","paragraph":"P2","skill":"詮釋整合"}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'taohuayuan-ji')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, updated_at = datetime('now')
  WHERE article_quizzes.edited_by IS NULL;

-- 愛蓮說
UPDATE articles SET notes = '公有領域經典，周敦頤（北宋）。約 120 字。要點底稿與閱讀測驗為 AI 撰寫，上線前請審稿老師過目。' WHERE id = 'ailian-shuo' AND notes IS NULL;
INSERT INTO article_keypoints (article_id, model, data_json) SELECT 'ailian-shuo', 'import', '{"centralIdea":"作者藉讚美蓮花出淤泥而不染的特質，表達自己追求君子品格、不隨俗追逐富貴的志向。","structure":"托物言志。先寫花（P1）：以陶淵明愛菊、世人愛牡丹襯托「予獨愛蓮」，並描寫蓮的形象；再論人（P2）：把菊、牡丹、蓮分別比作隱士、富貴者、君子，以三句感嘆作結。","vernacular":"水上、陸地上各種草木的花，值得喜愛的非常多。晉朝的陶淵明唯獨喜愛菊花；從唐朝以來，世人都很喜愛牡丹。我卻唯獨喜愛蓮花：它從污泥中長出來卻不被沾染，在清水中洗過卻不顯得妖豔；莖中間通透、外表挺直，不生藤蔓也不長枝節；香氣傳得越遠越清幽，筆直潔淨地立在水中，只能遠遠地欣賞，不能靠近玩弄。我認為菊花是花中的隱士，牡丹是花中的富貴者，蓮花是花中的君子。唉！喜愛菊花的，陶淵明以後就很少聽說了；喜愛蓮花的，和我一樣的還有誰呢？喜愛牡丹的，人應該很多吧！","keyPoints":[{"id":"KP1","text":"值得喜愛的花很多：陶淵明獨愛菊，唐代以來世人愛牡丹。","importance":"次要","paragraphs":["P1"]},{"id":"KP2","text":"作者獨愛蓮，因為它出淤泥而不染、濯清漣而不妖。","importance":"核心","paragraphs":["P1"]},{"id":"KP3","text":"蓮中通外直、不蔓不枝、香遠益清，可遠觀而不可褻玩，象徵君子正直端莊的品格。","importance":"核心","paragraphs":["P1"]},{"id":"KP4","text":"菊是花中的隱逸者，牡丹是富貴者，蓮是君子。","importance":"核心","paragraphs":["P2"]},{"id":"KP5","text":"愛菊者少、愛蓮者更少、愛牡丹者眾，感嘆世人多追求富貴，少有人追求君子之德。","importance":"核心","paragraphs":["P2"]}],"referenceOutline":[{"text":"引出愛蓮","children":[{"text":"可愛的花很多"},{"text":"陶淵明愛菊、世人愛牡丹"},{"text":"作者獨愛蓮"}]},{"text":"蓮的形象","children":[{"text":"出淤泥而不染"},{"text":"中通外直、香遠益清"},{"text":"可遠觀而不可褻玩"}]},{"text":"三種花的比喻","children":[{"text":"菊：隱逸者"},{"text":"牡丹：富貴者"},{"text":"蓮：君子"}]},{"text":"感嘆作結","children":[{"text":"愛蓮的人少、愛牡丹的人多"},{"text":"表明自己追求君子品格"}]}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'ailian-shuo')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, created_at = datetime('now');
INSERT INTO article_quizzes (article_id, model, data_json) SELECT 'ailian-shuo', 'import', '{"questions":[{"q":"文中哪一種花被比作「花之君子者」？","options":["菊","牡丹","蓮","桃花"],"answer":2,"explanation":"第二段「蓮，花之君子者也」；菊是隱逸者，牡丹是富貴者。","paragraph":"P2","skill":"擷取訊息"},{"q":"「出淤泥而不染」可以用來比喻哪一種人？","options":["身處不好的環境，仍能保持品格清白的人","喜歡整潔、常常打掃的人","出身貧窮後來變得富有的人","不喜歡和別人來往的人"],"answer":0,"explanation":"淤泥比喻污濁的環境，蓮從中長出卻不被沾染，比喻人在不良環境中依然潔身自好。","paragraph":"P1","skill":"詮釋整合"},{"q":"作者先寫陶淵明愛菊、世人愛牡丹，主要作用是什麼？","options":["說明菊花和牡丹比蓮花美","介紹歷史上有名的愛花人物","批評陶淵明的品味","襯托作者「獨愛蓮」的與眾不同"],"answer":3,"explanation":"先舉別人所愛，再說「予獨愛蓮」，用對比襯托出作者的選擇，也為第二段三種花的比喻鋪路。","paragraph":"P1","skill":"推論分析"},{"q":"「牡丹之愛，宜乎眾矣」這句話隱含作者什麼態度？","options":["讚美大家都懂得欣賞牡丹","感嘆世上追求富貴的人很多","希望更多人種植牡丹","認為牡丹是最美的花"],"answer":1,"explanation":"牡丹象徵富貴，愛牡丹的人很多，暗含對世人追逐名利的感嘆，和「蓮之愛，同予者何人」的孤單形成對比。","paragraph":"P2","skill":"推論分析"},{"q":"這篇文章藉描寫蓮花來表達作者的志向，這種寫法稱為什麼？","options":["借景抒情","托物言志","倒敘法","以對話推進情節"],"answer":1,"explanation":"作者寫的是蓮，真正要說的是自己想做君子、不隨俗追求富貴的志向，這是「托物言志」。","paragraph":"P2","skill":"詮釋整合"}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'ailian-shuo')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, updated_at = datetime('now')
  WHERE article_quizzes.edited_by IS NULL;

-- 醉翁亭記
UPDATE articles SET notes = '公有領域經典，歐陽脩（北宋）。約 400 字。要點底稿與閱讀測驗為 AI 撰寫，上線前請審稿老師過目。' WHERE id = 'zuiweng-ting-ji' AND notes IS NULL;
INSERT INTO article_keypoints (article_id, model, data_json) SELECT 'zuiweng-ting-ji', 'import', '{"centralIdea":"作者描寫醉翁亭一帶的山水美景，以及滁人同遊、太守宴飲之樂，表現他寄情山水、與民同樂的胸懷。","structure":"全文以「樂」字貫串。P1 由遠而近寫到醉翁亭並說明命名，點出「醉翁之意不在酒，在乎山水之間」；P2 寫山間朝暮與四時景色之樂；P3 寫滁人遊、太守宴、眾賓懽、太守醉；P4 寫日暮而歸，層層推出「太守之樂其樂」，最後點出作者身分。","vernacular":"滁州四面都是山，西南方的山峰林谷特別美，那樹木茂盛、幽深秀麗的是琅琊山。沿山路走六七里，聽到潺潺水聲，從兩峰之間流出的是釀泉。山勢迴轉、路也跟著轉彎，有座亭子像鳥張開翅膀一樣立在泉上，就是醉翁亭。亭是山裡的和尚智僊建的，名字是太守自己取的。太守常和客人來這裡喝酒，喝一點就醉，年紀又最大，所以自號醉翁。醉翁的心意不在酒，而在山水之間。山中早晚明暗變化，四季景色各不相同，所以遊賞的樂趣無窮。滁州人背著東西、扶老攜幼來往不絕；太守用溪魚、泉酒、野菜擺宴，賓客投壺下棋、喧鬧歡樂，白髮的太守醉倒在其中。傍晚夕陽下山，太守回去、賓客跟隨，鳥兒在林中歡叫。鳥兒只知道山林之樂，不知道人的快樂；人們只知道跟太守遊玩很快樂，卻不知道太守是以大家的快樂為快樂。醉了能和大家同樂，醒了能寫文章記述的，就是太守——廬陵的歐陽脩。","keyPoints":[{"id":"KP1","text":"由滁州群山寫到琅琊山、釀泉，再寫到醉翁亭，交代亭的位置。","importance":"次要","paragraphs":["P1"]},{"id":"KP2","text":"亭由僧人智僊所建；太守因「飲少輒醉，年又最高」自號醉翁，並以此為亭命名。","importance":"次要","paragraphs":["P1"]},{"id":"KP3","text":"「醉翁之意不在酒，在乎山水之間」點出主旨：真正的樂趣在山水。","importance":"核心","paragraphs":["P1"]},{"id":"KP4","text":"山間朝暮變化、四季景色不同，因此遊賞之樂無窮。","importance":"核心","paragraphs":["P2"]},{"id":"KP5","text":"滁人出遊、太守設宴、賓客歡樂、太守醉倒其間，呈現人人同樂的景象。","importance":"核心","paragraphs":["P3"]},{"id":"KP6","text":"日暮人歸，禽鳥樂、遊人樂，而太守以眾人之樂為樂，表現與民同樂。","importance":"核心","paragraphs":["P4"]},{"id":"KP7","text":"文末點出太守就是廬陵歐陽脩。","importance":"次要","paragraphs":["P4"]}],"referenceOutline":[{"text":"醉翁亭的位置與由來","children":[{"text":"由群山寫到琅琊山、釀泉、醉翁亭"},{"text":"智僊建亭、太守命名"},{"text":"醉翁之意在山水"}]},{"text":"山間景色之樂","children":[{"text":"朝暮的變化"},{"text":"四季的景色"}]},{"text":"遊宴之樂","children":[{"text":"滁人出遊"},{"text":"太守設宴、賓客歡樂"},{"text":"太守醉倒"}]},{"text":"日暮歸去","children":[{"text":"禽鳥之樂與遊人之樂"},{"text":"太守以眾人之樂為樂"},{"text":"點出作者歐陽脩"}]}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'zuiweng-ting-ji')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, created_at = datetime('now');
INSERT INTO article_quizzes (article_id, model, data_json) SELECT 'zuiweng-ting-ji', 'import', '{"questions":[{"q":"醉翁亭是誰建造的？","options":["太守歐陽脩","滁州的百姓","山中的僧人智僊","琅琊山的獵人"],"answer":2,"explanation":"第一段「作亭者誰？山之僧智僊也。名之者誰？太守自謂也。」建亭的是智僊，命名的才是太守。","paragraph":"P1","skill":"擷取訊息"},{"q":"太守為什麼自號「醉翁」？","options":["因為他每天都喝得大醉","因為他喝一點酒就醉，年紀又是最大的","因為皇帝賜給他這個稱號","因為亭子旁的泉水可以釀酒"],"answer":1,"explanation":"第一段「飲少輒醉，而年又最高，故自號曰醉翁也」。","paragraph":"P1","skill":"擷取訊息"},{"q":"「醉翁之意不在酒，在乎山水之間也」的意思最接近下列何者？","options":["太守真正喜愛的是山水之美，喝酒只是寄託","太守不喜歡喝酒，只是陪客人","太守想在山水間多蓋幾座亭子","太守認為山裡的酒比城裡好喝"],"answer":0,"explanation":"下一句「山水之樂，得之心而寓之酒也」說明：樂趣來自欣賞山水，酒只是寄託心情的媒介。","paragraph":"P1","skill":"詮釋整合"},{"q":"第三段依序寫了哪些場面？","options":["太守宴→滁人遊→太守醉→眾賓懽","滁人遊→太守宴→眾賓懽→太守醉","眾賓懽→太守醉→滁人遊→太守宴","太守醉→眾賓懽→太守宴→滁人遊"],"answer":1,"explanation":"第三段四個場面各以「……者，滁人遊也」「太守宴也」「眾賓懽也」「太守醉也」收尾，順序是遊、宴、懽、醉。","paragraph":"P3","skill":"擷取訊息"},{"q":"「人知從太守遊而樂，而不知太守之樂其樂也」表現了太守什麼樣的心境？","options":["因為當官而感到驕傲","對賓客不了解自己感到失望","只喜歡獨自欣賞山水","以百姓的快樂為自己的快樂"],"answer":3,"explanation":"「樂其樂」是「以他們的快樂為快樂」，太守看到百姓安樂而感到快樂，表現與民同樂的胸懷。","paragraph":"P4","skill":"推論分析"}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'zuiweng-ting-ji')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, updated_at = datetime('now')
  WHERE article_quizzes.edited_by IS NULL;

-- 岳陽樓記
UPDATE articles SET notes = '公有領域經典，范仲淹（北宋）。約 370 字。要點底稿與閱讀測驗為 AI 撰寫，上線前請審稿老師過目。' WHERE id = 'yueyang-lou-ji' AND notes IS NULL;
INSERT INTO article_keypoints (article_id, model, data_json) SELECT 'yueyang-lou-ji', 'import', '{"centralIdea":"作者藉登岳陽樓時因景物而生的悲、喜兩種心情，引出古仁人「不以物喜，不以己悲」「先天下之憂而憂，後天下之樂而樂」的胸懷，以此勉勵友人與自己。","structure":"P1 交代作記緣由；P2 概寫洞庭湖大觀，提出「覽物之情，得無異乎」；P3 寫陰雨景色與悲情；P4 寫春和晴明景色與喜情；P5 以古仁人之心和前兩種悲喜對照，提出「先憂後樂」的主旨；P6 記寫作時間。","vernacular":"慶曆四年春天，滕子京被貶到巴陵郡做太守。第二年，政事順利、百姓和樂，許多荒廢的事都興辦起來，於是重修岳陽樓，擴大原有的規模，刻上唐代和當代名人的詩賦，囑託我寫文章記述。我看巴陵最美的景色都在洞庭湖：它連著遠山、吞吐長江，水勢浩大、無邊無際，早晚陰晴，景象千變萬化，前人已經描述得很詳盡了。這裡北通巫峽，南到瀟湘，被貶的官員和詩人常在這裡聚會，他們看到景物的心情，能沒有不同嗎？如果遇到連月陰雨、陰風怒吼、濁浪滔天、日月無光，商旅不能通行，傍晚天色昏暗、虎嘯猿啼，這時登樓，就會想起離開京城、懷念家鄉，擔心被人毀謗譏諷，滿眼蕭條，悲傷到極點。如果遇到春天風和日麗、湖面平靜，天光水色一片碧綠，沙鷗飛翔、魚兒游動，岸邊花草茂盛；或是夜裡煙霧散盡、明月照耀千里，漁歌互相應答，這時登樓，就會心胸開闊、精神愉快，把榮辱都忘了，舉杯迎風，喜氣洋洋。唉！我曾探求古代仁人的心，他們和這兩種人不同。他們不因外物好壞而喜悲，也不因個人得失而喜悲；在朝廷做官就擔憂百姓，退居江湖就擔憂君主，進也憂、退也憂。那什麼時候才快樂呢？他們一定會說：「在天下人憂慮之前先憂慮，在天下人快樂之後才快樂。」唉！如果沒有這種人，我要跟誰同道呢？","keyPoints":[{"id":"KP1","text":"滕子京被貶到巴陵郡，一年後政通人和，重修岳陽樓並請作者寫記。","importance":"次要","paragraphs":["P1"]},{"id":"KP2","text":"岳陽樓的大觀在洞庭湖，氣象萬千；遷客騷人在此覽物，心情是否不同？","importance":"核心","paragraphs":["P2"]},{"id":"KP3","text":"陰雨連綿、濁浪排空時登樓，會去國懷鄉、憂讒畏譏，感極而悲。","importance":"核心","paragraphs":["P3"]},{"id":"KP4","text":"春和景明、皓月千里時登樓，會心曠神怡、寵辱偕忘，其喜洋洋。","importance":"核心","paragraphs":["P4"]},{"id":"KP5","text":"古仁人不以物喜、不以己悲，在朝憂民、在野憂君，進退都憂。","importance":"核心","paragraphs":["P5"]},{"id":"KP6","text":"主旨：「先天下之憂而憂，後天下之樂而樂」，並感嘆「微斯人，吾誰與歸」。","importance":"核心","paragraphs":["P5"]},{"id":"KP7","text":"文末記寫作時間：慶曆六年九月十五日。","importance":"次要","paragraphs":["P6"]}],"referenceOutline":[{"text":"作記緣由","children":[{"text":"滕子京被貶巴陵，政通人和"},{"text":"重修岳陽樓，囑託作記"}]},{"text":"洞庭大觀","children":[{"text":"銜遠山、吞長江，氣象萬千"},{"text":"遷客騷人覽物之情有何不同"}]},{"text":"覽物而悲","children":[{"text":"陰雨晦暗的景色"},{"text":"去國懷鄉，感極而悲"}]},{"text":"覽物而喜","children":[{"text":"春和景明與月夜的景色"},{"text":"心曠神怡，其喜洋洋"}]},{"text":"古仁人之心","children":[{"text":"不以物喜，不以己悲"},{"text":"進亦憂，退亦憂"},{"text":"先天下之憂而憂，後天下之樂而樂"}]},{"text":"寫作時間"}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'yueyang-lou-ji')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, created_at = datetime('now');
INSERT INTO article_quizzes (article_id, model, data_json) SELECT 'yueyang-lou-ji', 'import', '{"questions":[{"q":"作者為什麼寫這篇文章？","options":["皇帝命令他記錄洞庭湖的風景","滕子京重修岳陽樓後，請他寫文章記述","他被貶到巴陵，登樓抒發心情","為了參加科舉考試而寫"],"answer":1,"explanation":"第一段滕子京「乃重修岳陽樓……屬予作文以記之」，是受朋友囑託而寫。","paragraph":"P1","skill":"擷取訊息"},{"q":"第三段「霪雨霏霏」「陰風怒號」等景色，和登樓者什麼樣的心情相呼應？","options":["心曠神怡、寵辱偕忘","把酒臨風、其喜洋洋","滿目蕭然、感極而悲","平靜淡然、無憂無慮"],"answer":2,"explanation":"第三段寫陰雨晦暗的景色，結尾「滿目蕭然，感極而悲者矣」；喜的心情在第四段。","paragraph":"P3","skill":"詮釋整合"},{"q":"第三、四段分別寫悲與喜，作者安排這兩段的主要目的是什麼？","options":["證明洞庭湖的天氣變化很大","勸人不要在雨天登樓","說明遷客騷人很會寫詩","作為對照，引出不受外物影響的古仁人之心"],"answer":3,"explanation":"第五段「或異二者之為」，說古仁人和前面因景而悲、因景而喜的兩種人不同，可見前兩段是為了對照、襯托主旨。","paragraph":"P5","skill":"推論分析"},{"q":"「不以物喜，不以己悲」的意思最接近下列何者？","options":["不因外在環境的好壞或個人的得失而大喜大悲","不喜歡美好的景物，也不為自己難過","只關心別人，完全不在乎自己","看到景物要保持冷靜，不能有情緒"],"answer":0,"explanation":"「物」指外物、環境，「己」指個人遭遇；意思是心情不隨外在環境和自身得失而起伏。","paragraph":"P5","skill":"詮釋整合"},{"q":"下列哪一種行為最符合「先天下之憂而憂，後天下之樂而樂」的精神？","options":["考試考好了就立刻出去慶祝","班長等大家的問題都解決、安心了，自己才放鬆休息","遇到困難先照顧好自己再說","自己快樂的時候才去關心別人"],"answer":1,"explanation":"先憂在眾人之前、樂在眾人之後，把大家的事放在自己的享樂前面；班長的做法最接近。","paragraph":"P5","skill":"比較評估"}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'yueyang-lou-ji')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, updated_at = datetime('now')
  WHERE article_quizzes.edited_by IS NULL;

-- 師說
UPDATE articles SET notes = '公有領域經典，韓愈（唐）。約 460 字。要點底稿與閱讀測驗為 AI 撰寫，上線前請審稿老師過目。' WHERE id = 'shi-shuo' AND notes IS NULL;
INSERT INTO article_keypoints (article_id, model, data_json) SELECT 'shi-shuo', 'import', '{"centralIdea":"韓愈論述從師學習的必要，主張「道之所存，師之所存」，不論貴賤長幼都應向有道的人學習，並批評當時士大夫恥於從師的風氣。","structure":"P1 正面立論：老師的作用是傳道、受業、解惑，人都有惑所以要從師，擇師看「道」而不看年齡貴賤；P2 反面批評：用古聖人與今眾人、為子擇師與自己恥師、百工與士大夫三組對比，批評恥學於師；P3 舉孔子為例，說明聖人無常師、「聞道有先後，術業有專攻」；P4 交代寫作緣由：贈給好學古文的李蟠。","vernacular":"古代求學的人一定有老師。老師是傳授道理、教授學業、解答疑惑的人。人不是生下來就懂得道理，誰能沒有疑惑？有疑惑卻不向老師請教，那疑惑就永遠解不開。比我早出生的人，懂得道理比我早，我向他學習；比我晚出生的人，如果懂得道理也比我早，我也向他學習。我學的是道理，哪管他年紀比我大還是小呢？所以不論地位貴賤、年紀長幼，道理在哪裡，老師就在哪裡。唉！從師的風氣失傳很久了，要人沒有疑惑很難啊！古代的聖人遠遠超過一般人，還向老師請教；現在的一般人遠不如聖人，卻以向老師學習為恥，所以聖人更聖明，愚人更愚昧。有人愛自己的孩子，替他選老師，自己卻以從師為恥，真是糊塗。孩子的老師只教讀書斷句，不是我說的傳道解惑的老師；斷句不懂要問，疑惑不解反而不問，學了小的丟了大的。巫醫、樂師、工匠不以互相學習為恥，士大夫聽到有人稱師稱弟子，卻聚在一起取笑，說兩人年紀差不多、學問也差不多，拜地位低的人為師覺得羞恥，拜官大的人為師又近乎諂媚。士大夫看不起巫醫、樂師、工匠，現在智慧反而比不上他們，真奇怪啊！聖人沒有固定的老師，孔子曾向郯子、萇弘、師襄、老聃學習，這些人的賢能都比不上孔子。孔子說：「三個人同行，其中一定有可以當我老師的人。」所以學生不一定不如老師，老師不一定比學生賢能；只是懂得道理有先後，學問技藝各有專長罷了。李家的孩子李蟠，十七歲，喜愛古文，六經都學過了，不受時俗拘束，跟我學習。我讚賞他能實行古人從師之道，寫了這篇〈師說〉送給他。","keyPoints":[{"id":"KP1","text":"老師的作用是傳道、受業、解惑。","importance":"核心","paragraphs":["P1"]},{"id":"KP2","text":"人不是生來就懂，有疑惑不從師就永遠解不開。","importance":"次要","paragraphs":["P1"]},{"id":"KP3","text":"擇師的標準是「道」，不論貴賤長幼：道之所存，師之所存。","importance":"核心","paragraphs":["P1"]},{"id":"KP4","text":"以三組對比批評恥學於師的風氣：古聖人從師而今眾人恥師、為子擇師而自己恥師、百工不恥相師而士大夫笑之。","importance":"核心","paragraphs":["P2"]},{"id":"KP5","text":"聖人無常師，孔子也曾向郯子等人學習；弟子不必不如師，聞道有先後，術業有專攻。","importance":"核心","paragraphs":["P3"]},{"id":"KP6","text":"寫作緣由：李蟠好古文、不拘於時而從作者學習，作〈師說〉贈他。","importance":"次要","paragraphs":["P4"]}],"referenceOutline":[{"text":"從師的必要","children":[{"text":"老師：傳道、受業、解惑"},{"text":"人皆有惑，須從師"},{"text":"道之所存，師之所存"}]},{"text":"批評恥學於師","children":[{"text":"古之聖人與今之眾人"},{"text":"為子擇師與自己恥師"},{"text":"百工不恥相師與士大夫笑之"}]},{"text":"聖人無常師","children":[{"text":"孔子師郯子等人"},{"text":"聞道有先後，術業有專攻"}]},{"text":"寫作緣由","children":[{"text":"李蟠好古文、能行古道"}]}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'shi-shuo')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, created_at = datetime('now');
INSERT INTO article_quizzes (article_id, model, data_json) SELECT 'shi-shuo', 'import', '{"questions":[{"q":"韓愈認為老師的作用是什麼？","options":["教人讀書識字、學習斷句","傳道、受業、解惑","幫學生考取功名","管教學生的品行"],"answer":1,"explanation":"第一段「師者，所以傳道、受業、解惑也」。第二段還特別說只教「句讀」的不是他所說的老師。","paragraph":"P1","skill":"擷取訊息"},{"q":"根據第一段，選擇老師最主要的標準是什麼？","options":["年紀比自己大","地位比自己高","有沒有「道」","名氣大不大"],"answer":2,"explanation":"「無貴無賤，無長無少，道之所存，師之所存也」，看的是對方是否懂得道理，而不是年齡或地位。","paragraph":"P1","skill":"擷取訊息"},{"q":"作者說士大夫「愛其子，擇師而教之；於其身也，則恥師焉，惑矣」，是在批評什麼？","options":["士大夫不愛自己的孩子","士大夫替孩子挑錯了老師","士大夫的孩子不用功","士大夫替孩子找老師，自己卻以向人學習為恥"],"answer":3,"explanation":"同樣是學習，對孩子肯請老師，對自己卻覺得丟臉，作者認為這種矛盾很糊塗（惑矣）。","paragraph":"P2","skill":"推論分析"},{"q":"「聞道有先後，術業有專攻」最能支持下列哪一個觀點？","options":["弟子不一定不如老師，老師也不一定比弟子賢能","年紀越大的人越有學問","每個人一輩子只能學一種技藝","老師永遠比學生懂得多"],"answer":0,"explanation":"第三段在這句之前說「弟子不必不如師，師不必賢於弟子」，理由就是懂得道理有早晚、專長各不相同。","paragraph":"P3","skill":"詮釋整合"},{"q":"作者寫這篇文章送給誰？為什麼？","options":["送給孔子，表達敬佩","送給士大夫，勸他們改過","送給李蟠，嘉許他好學古文、能行古道","送給自己的兒子，勉勵他讀書"],"answer":2,"explanation":"第四段「李氏子蟠……學於余。余嘉其能行古道，作師說以貽之」。","paragraph":"P4","skill":"擷取訊息"}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'shi-shuo')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, updated_at = datetime('now')
  WHERE article_quizzes.edited_by IS NULL;

-- 出師表
UPDATE articles SET notes = '公有領域經典，諸葛亮（三國蜀漢）。約 630 字。要點底稿與閱讀測驗為 AI 撰寫，上線前請審稿老師過目。' WHERE id = 'chu-shi-biao' AND notes IS NULL;
INSERT INTO article_keypoints (article_id, model, data_json) SELECT 'chu-shi-biao', 'import', '{"centralIdea":"諸葛亮在出師北伐前上表劉禪，勸他廣開言路、賞罰公平、親賢遠佞，並陳述自己受先帝知遇之恩、誓死北伐興復漢室的忠誠。","structure":"P1–P5 勸諫：分析形勢後勸開張聖聽（P1）、賞罰一致（P2），推薦郭攸之、費禕、董允、向寵等賢臣（P3–P4），以兩漢興衰勸親賢遠佞（P5）；P6–P7 自述：布衣出身、受三顧之恩，受命以來南方已定，當北定中原；P8 分派責任並再勸劉禪自謀；P9 臨表涕零作結。","vernacular":"臣諸葛亮上言：先帝開創大業還沒完成一半就去世了。現在天下分成三國，益州人力物力疲乏，這真是危急存亡的時刻。但宮中侍衛不敢懈怠，在外的將士奮不顧身，都是感念先帝的特殊恩遇，想報答在陛下身上。陛下應該廣開言路，發揚先帝的美德，振奮志士的精神；不應該看輕自己，說話不合道理，堵塞忠臣進諫的路。宮中和丞相府是一體的，獎懲不應該有不同標準；犯法的和盡忠行善的，都應交給主管官員論定賞罰，不可偏私。郭攸之、費禕、董允等人忠誠可靠，宮中的事都可以先問他們再施行；將軍向寵品性善良、熟悉軍事，軍中的事都可以問他。親近賢臣、疏遠小人，是西漢興盛的原因；親近小人、疏遠賢臣，是東漢衰敗的原因。臣本來是平民，在南陽耕田，只求在亂世保全性命，不想在諸侯間求名。先帝不嫌臣身分低微、見識淺陋，親自三次到草屋拜訪，問臣天下大事，臣因此感動，答應為先帝奔走效力。後來遇到兵敗，在危難中接受任命，到現在已經二十一年了。先帝知道臣謹慎，臨終把大事託付給臣。受命以來臣日夜憂慮，怕辜負託付；所以五月渡過瀘水，深入荒涼之地。現在南方已經平定，兵器盔甲也充足，應當率領三軍北上平定中原，興復漢室，回到舊都。這是臣報答先帝、效忠陛下的本分。希望陛下把討賊興復的任務交給臣，如果沒有成效，就治臣的罪；如果沒有進獻振興德政的忠言，就追究郭攸之等人的怠慢。陛下也應該自己多考慮，詢問治國的好方法，採納正確的意見。臣受恩深重，非常感激。如今就要遠離，面對這份奏表不禁落淚，不知道自己說了些什麼。","keyPoints":[{"id":"KP1","text":"先帝中途去世，天下三分、益州疲弊，正是危急存亡之時。","importance":"次要","paragraphs":["P1"]},{"id":"KP2","text":"勸劉禪廣開言路（開張聖聽），不可妄自菲薄、堵塞忠諫之路。","importance":"核心","paragraphs":["P1"]},{"id":"KP3","text":"宮中與府中賞罰要一致，不可偏私。","importance":"核心","paragraphs":["P2"]},{"id":"KP4","text":"推薦郭攸之、費禕、董允主持宮中之事，向寵主持營中之事。","importance":"次要","paragraphs":["P3","P4"]},{"id":"KP5","text":"以先漢興隆、後漢傾頹為鑑，勸劉禪親賢臣、遠小人。","importance":"核心","paragraphs":["P5"]},{"id":"KP6","text":"自述布衣出身，感激先帝三顧茅廬，受任於敗軍之際已二十一年。","importance":"核心","paragraphs":["P6"]},{"id":"KP7","text":"受先帝託付，南方已定，決心北定中原、興復漢室，以報先帝、忠陛下。","importance":"核心","paragraphs":["P7"]},{"id":"KP8","text":"請求把討賊重任交給自己，失敗甘願受罰；並勸劉禪諮諏善道、察納雅言。","importance":"次要","paragraphs":["P8"]}],"referenceOutline":[{"text":"勸諫後主","children":[{"text":"形勢危急，勸開張聖聽"},{"text":"賞罰一致，不可偏私"},{"text":"推薦郭攸之、費禕、董允、向寵"},{"text":"親賢臣、遠小人"}]},{"text":"自述心志","children":[{"text":"布衣躬耕，先帝三顧草廬"},{"text":"受命以來夙夜憂歎，南方已定"},{"text":"北定中原，興復漢室"}]},{"text":"分責與叮嚀","children":[{"text":"自己負責討賊"},{"text":"郭攸之等人負責進言"},{"text":"陛下宜自謀，察納雅言"}]},{"text":"臨表涕零"}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'chu-shi-biao')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, created_at = datetime('now');
INSERT INTO article_quizzes (article_id, model, data_json) SELECT 'chu-shi-biao', 'import', '{"questions":[{"q":"諸葛亮說「此誠危急存亡之秋也」，是根據什麼形勢判斷的？","options":["南方叛亂還沒平定","朝中大臣彼此爭權","先帝去世、天下三分，益州人力物力疲乏","曹操即將攻打成都"],"answer":2,"explanation":"第一段「先帝創業未半，而中道崩殂。今天下三分，益州疲弊」，接著才說「此誠危急存亡之秋也」。","paragraph":"P1","skill":"擷取訊息"},{"q":"下列何者不是諸葛亮向劉禪提出的建議？","options":["廣開言路，聽取忠臣的意見","賞罰公平，宮中府中一致","親近賢臣，遠離小人","把宮中大小事都交給宦官處理"],"answer":3,"explanation":"文中建議宮中之事「悉以咨之」的是郭攸之、費禕、董允等賢臣，並沒有要交給宦官；其餘三項分見第一、二、五段。","paragraph":"P3","skill":"擷取訊息"},{"q":"「先帝不以臣卑鄙，猥自枉屈，三顧臣於草廬之中」，這裡的「卑鄙」是什麼意思？","options":["品德低劣、手段卑劣","身分低微、見識淺陋","年紀太輕、經驗不足","不肯出來做官"],"answer":1,"explanation":"古文的「卑」指地位低，「鄙」指見識淺，是諸葛亮的自謙，和現代「卑鄙」指品德惡劣的意思不同。","paragraph":"P6","skill":"詮釋整合"},{"q":"諸葛亮在文中一再提到「先帝」，最主要的用意是什麼？","options":["提醒劉禪不忘先帝的遺德與託付，加強勸諫的力量","炫耀自己和先帝的交情","批評先帝生前的作為","表示自己只效忠先帝，不效忠劉禪"],"answer":0,"explanation":"他以先帝的遺德、識人與臨終託付來勸劉禪納諫用賢，也說明自己北伐是為了「報先帝而忠陛下」。","paragraph":"P7","skill":"推論分析"},{"q":"從全文看，諸葛亮寫這篇表的心情最接近下列何者？","options":["對劉禪失望，想辭官歸隱","對北伐沒有把握，想推卸責任","感念先帝知遇之恩，忠心懇切又放心不下後主","得意自己的功勞，希望得到封賞"],"answer":2,"explanation":"文中反覆叮嚀劉禪納諫用賢，又自述受恩感激、願擔討賊重任，最後「臨表涕零，不知所言」，可見忠誠懇切又牽掛後主。","paragraph":"P9","skill":"詮釋整合"}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'chu-shi-biao')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, updated_at = datetime('now')
  WHERE article_quizzes.edited_by IS NULL;

-- 赤壁賦
UPDATE articles SET notes = '公有領域經典，蘇軾（北宋）。約 540 字。要點底稿與閱讀測驗為 AI 撰寫，上線前請審稿老師過目。' WHERE id = 'qian-chibi-fu' AND notes IS NULL;
INSERT INTO article_keypoints (article_id, model, data_json) SELECT 'qian-chibi-fu', 'import', '{"centralIdea":"作者記與客夜遊赤壁，情緒由樂而悲、由悲轉喜，藉水與月說明變與不變的道理，表現他身處逆境仍超然曠達的人生態度。","structure":"以主客問答推展，情感為「樂→悲→喜」：P1 月夜泛舟之樂；P2 扣舷而歌，洞簫悲涼，由樂轉悲；P3 客借曹操英雄已逝與人生短暫而悲；P4 蘇子以水月為喻說明變與不變，並共享清風明月；P5 客喜而笑，醉臥舟中至天明。","vernacular":"壬戌年秋天，七月十六日，我和客人坐船在赤壁下遊玩。清風緩緩吹來，水面平靜無波。我舉杯勸客人喝酒，吟誦描寫明月的詩篇。不久月亮從東山升起，在星宿間徘徊，白茫茫的霧氣籠罩江面，水光和天色連成一片。我們任小船漂流，越過茫茫江面，好像凌空駕風，不知道要停在哪裡；又好像離開人世，飛升成仙。這時酒喝得很快樂，敲著船舷唱歌。有位客人吹洞簫伴奏，簫聲嗚嗚咽咽，像哀怨、像思慕、像哭泣、像傾訴，餘音細長不斷。我神色轉為憂愁，整好衣襟坐直，問客人為什麼吹得這麼悲涼。客人說：這裡是當年曹操被周瑜圍困的地方。曹操攻下荊州、順流東下時，戰船千里、旌旗蔽空，對江飲酒、橫槊賦詩，真是一代英雄，如今又在哪裡呢？何況我們只是在江邊打魚砍柴的平凡人，像蜉蝣一樣寄生在天地間，渺小得像大海中的一粒米。感嘆人生短暫，羨慕長江無窮，想和神仙同遊、與明月長存，又知道不可能輕易得到，只好把簫聲寄託在悲涼的秋風裡。我說：你也知道水和月嗎？江水不停流去，卻從沒有真正流走；月亮有圓有缺，最終也沒有增減。從變的角度看，天地連一眨眼的時間都不能不變；從不變的角度看，萬物和我們都是無窮無盡的，又何必羨慕呢？天地間萬物各有主人，不是我的，一絲一毫也不拿。只有江上的清風和山間的明月，耳朵聽到成為聲音，眼睛看到成為景色，拿取不受禁止，使用也用不完，這是大自然無窮的寶藏，是我和你可以共同享受的。客人聽了高興地笑了，洗淨酒杯重新斟酒。菜餚果品吃完了，杯盤散亂一片。大家互相枕靠著睡在船上，不知道東方已經發白。","keyPoints":[{"id":"KP1","text":"秋夜與客泛舟赤壁，清風明月，飄飄然如羽化登仙，心情愉快。","importance":"核心","paragraphs":["P1"]},{"id":"KP2","text":"飲酒放歌，客吹洞簫，簫聲如怨如慕、如泣如訴，情緒由樂轉悲。","importance":"次要","paragraphs":["P2"]},{"id":"KP3","text":"客想起曹操一世之雄而今安在，感嘆人生短暫渺小，羨慕長江無窮。","importance":"核心","paragraphs":["P3"]},{"id":"KP4","text":"蘇子以水與月為喻：從變的角度看，天地一瞬也在變；從不變的角度看，物與我皆無盡。","importance":"核心","paragraphs":["P4"]},{"id":"KP5","text":"物各有主不可強取，唯有江上清風、山間明月取之無禁、用之不竭，可以共同享受。","importance":"核心","paragraphs":["P4"]},{"id":"KP6","text":"客聽了轉悲為喜，洗盞更酌，醉臥舟中直到天亮。","importance":"次要","paragraphs":["P5"]}],"referenceOutline":[{"text":"月夜泛舟之樂","children":[{"text":"清風徐來，月出東山"},{"text":"如羽化而登仙"}]},{"text":"由樂轉悲","children":[{"text":"扣舷而歌"},{"text":"洞簫聲如怨如慕"}]},{"text":"客人之悲","children":[{"text":"曹操一世之雄而今安在"},{"text":"人生短暫、渺小如滄海一粟"}]},{"text":"蘇子的開解","children":[{"text":"水與月：變與不變"},{"text":"物各有主，不取非分之物"},{"text":"共享清風明月"}]},{"text":"轉悲為喜","children":[{"text":"洗盞更酌"},{"text":"醉臥舟中到天亮"}]}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'qian-chibi-fu')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, created_at = datetime('now');
INSERT INTO article_quizzes (article_id, model, data_json) SELECT 'qian-chibi-fu', 'import', '{"questions":[{"q":"本文的情感變化，依序是下列何者？","options":["悲→樂→悲","樂→悲→喜","喜→怒→樂","悲→喜→悲"],"answer":1,"explanation":"開頭月夜泛舟「飲酒樂甚」，接著簫聲與客人的感嘆轉為悲，最後聽了蘇子的話「客喜而笑」。","paragraph":"P5","skill":"詮釋整合"},{"q":"客人悲傷的主要原因是什麼？","options":["擔心回家的路太遠","想念遠方的親人","感嘆英雄終將消逝，人生短暫而渺小","不喜歡蘇子唱的歌"],"answer":2,"explanation":"第三段客人說曹操「固一世之雄也，而今安在哉」，又「哀吾生之須臾，羨長江之無窮」。","paragraph":"P3","skill":"擷取訊息"},{"q":"「寄蜉蝣於天地，渺滄海之一粟」用什麼方式表現人的渺小？","options":["以生命短暫的小蟲和大海中的一粒米作比喻","用誇張的數字描寫","用人物對話說明","舉曹操的故事作證"],"answer":0,"explanation":"蜉蝣朝生暮死，比喻人生短暫；一粒米放在大海裡，比喻人在天地間的渺小。","paragraph":"P3","skill":"詮釋整合"},{"q":"蘇子說「自其不變者而觀之，則物與我皆無盡也」，他想勸客人什麼？","options":["應該趕快建功立業","換一個角度看，就不必羨慕長江的無窮","人生確實很短，應該悲傷","要努力修行才能成仙"],"answer":1,"explanation":"客人「羨長江之無窮」，蘇子說從不變的角度看，萬物和我們一樣無窮無盡，所以接著說「而又何羨乎」。","paragraph":"P4","skill":"推論分析"},{"q":"蘇子認為什麼是「取之無禁，用之不竭」、可以和客人一起享受的？","options":["美酒和佳餚","名聲和地位","赤壁的古戰場遺跡","江上的清風與山間的明月"],"answer":3,"explanation":"第四段「惟江上之清風，與山間之明月……取之無禁，用之不竭，是造物者之無盡藏也，而吾與子之所共適」。","paragraph":"P4","skill":"擷取訊息"}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'qian-chibi-fu')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, updated_at = datetime('now')
  WHERE article_quizzes.edited_by IS NULL;

-- 匆匆
UPDATE articles SET notes = '公有領域經典，朱自清（民國（1922））。約 540 字。要點底稿與閱讀測驗為 AI 撰寫，上線前請審稿老師過目。' WHERE id = 'congcong' AND notes IS NULL;
INSERT INTO article_keypoints (article_id, model, data_json) SELECT 'congcong', 'import', '{"centralIdea":"作者透過對日子一去不復返的追問與描寫，抒發時光匆匆流逝、自己卻虛度光陰的惋惜與不甘。","structure":"首尾呼應：P1 以燕子、楊柳、桃花能再來，對比日子一去不復返，提出疑問；P2 算出八千多日已溜走而感傷；P3 具體描寫日子在生活細節中匆匆流逝；P4 反省自己在匆匆中只有徘徊、沒有留下痕跡；P5 重複開頭的問句作結。","vernacular":null,"keyPoints":[{"id":"KP1","text":"燕子、楊柳、桃花都能再來，日子卻一去不復返，作者因此提出疑問。","importance":"核心","paragraphs":["P1"]},{"id":"KP2","text":"八千多個日子像針尖上的水滴落入大海，無聲無影地溜走。","importance":"核心","paragraphs":["P2"]},{"id":"KP3","text":"日子在洗手、吃飯、默默、睡覺時從身邊匆匆過去，想挽留也留不住。","importance":"核心","paragraphs":["P3"]},{"id":"KP4","text":"作者反省自己在匆匆中只有徘徊，沒有留下痕跡，不甘心白白走這一遭。","importance":"核心","paragraphs":["P4"]},{"id":"KP5","text":"結尾重複開頭的問句，首尾呼應，加深對時光流逝的感慨。","importance":"次要","paragraphs":["P5"]}],"referenceOutline":[{"text":"提出疑問","children":[{"text":"燕子、楊柳、桃花都能再來"},{"text":"日子為什麼一去不復返"}]},{"text":"日子已經溜走","children":[{"text":"八千多個日子"},{"text":"像水滴落入大海，無聲無影"}]},{"text":"日子如何匆匆","children":[{"text":"洗手、吃飯、默默時溜過"},{"text":"想遮挽也留不住"}]},{"text":"自我反省","children":[{"text":"只有徘徊，沒有留下痕跡"},{"text":"不甘白白走這一遭"}]},{"text":"再次追問（首尾呼應）"}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'congcong')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, created_at = datetime('now');
INSERT INTO article_quizzes (article_id, model, data_json) SELECT 'congcong', 'import', '{"questions":[{"q":"第一段先寫燕子、楊柳、桃花，目的是什麼？","options":["介紹春天的美景","說明作者喜歡大自然","和一去不復返的日子形成對比","表示作者住在鄉下"],"answer":2,"explanation":"燕子會再來、楊柳會再青、桃花會再開，「但是」日子卻一去不復返，用能再來的事物反襯時間的不能回頭。","paragraph":"P1","skill":"推論分析"},{"q":"作者說已經有「八千多日子」從手中溜去，大約是多少時間？","options":["二十多年","八年","八十年","兩年多"],"answer":0,"explanation":"一年約三百六十五天，八千多天大約是二十二年，也就是作者寫作時的年紀。","paragraph":"P2","skill":"推論分析"},{"q":"「像針尖上一滴水滴在大海裡」這個比喻主要表現什麼？","options":["作者很喜歡看海","日子消逝得無聲無息，渺小得找不回來","時間像海水一樣會漲潮退潮","作者的眼淚很多"],"answer":1,"explanation":"後面接著說「我的日子滴在時間的流裡，沒有聲音，也沒有影子」，強調日子悄悄消失、無從找回。","paragraph":"P2","skill":"詮釋整合"},{"q":"第三段寫洗手、吃飯、躺在床上時日子悄悄過去，這樣寫有什麼效果？","options":["說明作者生活很規律","批評作者太懶惰","教讀者如何安排一天","用具體的生活細節，讓抽象的時間流逝變得看得見"],"answer":3,"explanation":"時間本來看不見，作者把它寫成從水盆、飯碗、雙眼前「過去」，讓讀者具體感受到日子的匆匆。","paragraph":"P3","skill":"詮釋整合"},{"q":"文章最後再問一次「我們的日子為什麼一去不復返呢？」，這種寫法稱為什麼？","options":["首尾呼應","開門見山","先抑後揚","倒敘"],"answer":0,"explanation":"結尾重複第一段的問句，前後呼應，讓全文結構完整，也加深感慨。","paragraph":"P5","skill":"詮釋整合"}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'congcong')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, updated_at = datetime('now')
  WHERE article_quizzes.edited_by IS NULL;

-- 落花生
UPDATE articles SET notes = '公有領域經典，許地山（民國（1922））。約 480 字。要點底稿與閱讀測驗為 AI 撰寫，上線前請審稿老師過目。' WHERE id = 'luo-huasheng' AND notes IS NULL;
INSERT INTO article_keypoints (article_id, model, data_json) SELECT 'luo-huasheng', 'import', '{"centralIdea":"藉一家人過花生收穫節時父親談花生的可貴，說明做人要像花生一樣踏實有用，不求外表的偉大體面。","structure":"依事情發展敘述，略寫種與收、詳寫議花生：P1 種花生、收穫；P2 母親提議過收穫節；P3 大家說花生的好處；P4 父親說出花生最可貴之處；P5 父親由花生說到做人的道理；P6 以父親的話印在心版上作結。","vernacular":null,"keyPoints":[{"id":"KP1","text":"母親提議把屋後空地闢成花生園，孩子們一起種，幾個月後就收穫了。","importance":"次要","paragraphs":["P1"]},{"id":"KP2","text":"母親提議辦收穫節，把花生做成多種食品，在園裡的茅亭舉行。","importance":"次要","paragraphs":["P2"]},{"id":"KP3","text":"父親問花生的好處：姊姊說氣味美，哥哥說可以製油，「我」說便宜、人人愛吃。","importance":"次要","paragraphs":["P3"]},{"id":"KP4","text":"父親指出花生可貴之處：不像蘋果、桃子、石榴把果實高掛枝頭，而是埋在地底，成熟了才讓人挖出來。","importance":"核心","paragraphs":["P4"]},{"id":"KP5","text":"父親勉勵孩子要像花生，做有用的人，不要做只求偉大、體面的人。","importance":"核心","paragraphs":["P5"]},{"id":"KP6","text":"父親的話一直印在「我」的心版上。","importance":"核心","paragraphs":["P6"]}],"referenceOutline":[{"text":"種花生、收花生","children":[{"text":"母親提議闢花生園"},{"text":"大家分工，幾個月後收穫"}]},{"text":"過收穫節","children":[{"text":"母親準備花生食品"},{"text":"父親也來參加"}]},{"text":"談花生","children":[{"text":"孩子們說花生的好處"},{"text":"父親說花生把果實埋在地底"}]},{"text":"做人的道理","children":[{"text":"要像花生，做有用的人"},{"text":"不做只求偉大、體面的人"}]},{"text":"父親的話印在心上"}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'luo-huasheng')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, created_at = datetime('now');
INSERT INTO article_quizzes (article_id, model, data_json) SELECT 'luo-huasheng', 'import', '{"questions":[{"q":"花生園是怎麼來的？","options":["父親買了一塊田給孩子們","母親提議把屋後半畝空地闢來種花生","鄰居送給他們的","學校要求學生種植"],"answer":1,"explanation":"第一段「我們屋後有半畝隙地」，母親說讓它荒著可惜，「就闢來做花生園罷」。","paragraph":"P1","skill":"擷取訊息"},{"q":"下列哪一個「花生的好處」是「我」說的？","options":["氣味很美","可以製油","把果實埋在地底","價錢便宜，人人都買得起、都喜歡吃"],"answer":3,"explanation":"第三段姊姊說氣味美，哥哥說可製油，「我」說「無論何等人都可以用賤價買它來吃；都喜歡吃它」。埋在地底是父親說的。","paragraph":"P3","skill":"擷取訊息"},{"q":"父親拿蘋果、桃子、石榴和花生比較，是為了突顯花生的什麼特點？","options":["果實不外露，不炫耀自己","顏色比較鮮豔好看","味道比水果更甜","種起來比較容易"],"answer":0,"explanation":"蘋果等把鮮豔的果實「懸在枝上」讓人羨慕，花生卻「只把果子埋在地底」，用對比突顯花生樸實、不炫耀。","paragraph":"P4","skill":"比較評估"},{"q":"父親說「你們要像花生」，他希望孩子成為什麼樣的人？","options":["外表體面、受人羨慕的人","踏實有用、不求表面光彩的人","很會種田的人","愛吃花生的人"],"answer":1,"explanation":"第五段「因為它是有用的，不是偉大、好看的東西」，「我」也體會到「人要做有用的人，不要做偉大、體面的人」。","paragraph":"P5","skill":"推論分析"},{"q":"最後一段說父親的話「現在還印在我心版上」，表示什麼？","options":["作者把父親的話刻在木板上","作者覺得父親說話太嚴厲","那晚的花生食品非常好吃","父親的教誨對作者影響深遠，一直記在心裡"],"answer":3,"explanation":"「心版」是把心比作可以刻印的版子，意思是父親的話深深記在心中，到現在都沒忘。","paragraph":"P6","skill":"詮釋整合"}]}' WHERE EXISTS (SELECT 1 FROM articles WHERE id = 'luo-huasheng')
  ON CONFLICT(article_id) DO UPDATE SET model = excluded.model, data_json = excluded.data_json, updated_at = datetime('now')
  WHERE article_quizzes.edited_by IS NULL;
